#!/bin/sh
lang=$1
text=$2
pitch=40
speed=130

#dirty fix for french phoneme acting weird from web interface
#while in command line it works great
#I search for encoding problems but I haven't found any solution

if [ $# -eq 1 ];then
	text=$lang
	lang="en"
fi

if [ -z "$lang" ];then
	text=$lang
	lang="en"
fi

if [ -z "$text" ];then
	text="Hello world"
fi

if [ $lang = "fr" ]
	then
	text=$(echo "$text" |sed "s/é/ai/g")
	text=$(echo "$text" |sed "s/è/ai/g")
	text=$(echo "$text" |sed "s/à/a/g")
	text=$(echo "$text" |sed "s/ù/u/g")
fi
#echo $text > /tmp/log
/show/listecho "Say $text with Espeak" $OK
/usr/bin/espeak -p $pitch -s $speed -v $lang "$text" --stdout|aplay
